name: carnation-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-airway
  - bioconductor-clusterprofiler
  - bioconductor-degreport
  - bioconductor-deseq2
  - bioconductor-enrichplot
  - bioconductor-genetonic
  - bioconductor-matrixgenerics
  - bioconductor-org.hs.eg.db
  - bioconductor-summarizedexperiment
  - r-base>=4.0
  - r-colorspace
  - r-complexupset
  - r-dendextend
  - r-dplyr
  - r-dt
  - r-ggplot2
  - r-ggrepel
  - r-heatmaply
  - r-igraph
  - r-plotly
  - r-readr
  - r-reticulate
  - r-rintrojs
  - r-scales
  - r-shiny
  - r-shinybs
  - r-shinycssloaders
  - r-shinythemes
  - r-shinywidgets
  - r-sortable
  - r-viridis
  - r-viridislite
  - r-visnetwork
  - r-yaml
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - pandoc
  - pdflatex
  - plotly
  - python-kaleido
  - qpdf

